/**
 * PDF Export Utility
 * 
 * Generates PDF reports for CVSS vulnerability assessments
 */

// html2pdf is a browser-only library that assumes `self`/`window` exist.
// Import it dynamically inside the export function to avoid SSR errors
// (e.g., `self is not defined`) when the module is loaded on the server.

export interface PDFExportOptions {
  version: string;
  score: number;
  severity: string;
  vectorString: string;
  metrics: Record<string, string>;
}

/**
 * Generate a PDF report for a CVSS assessment
 */
export async function exportToPDF(options: PDFExportOptions): Promise<void> {
  const { version, score, severity, vectorString, metrics } = options;
  const timestamp = new Date().toLocaleString();

  // Create HTML content for PDF
  const content = `
    <div style="font-family: system-ui, -apple-system, sans-serif; padding: 40px; max-width: 800px;">
      <div style="text-align: center; margin-bottom: 40px;">
        <h1 style="color: #18181b; margin-bottom: 8px;">CVSS v${version} Assessment Report</h1>
        <p style="color: #71717a; font-size: 14px;">Generated: ${timestamp}</p>
      </div>

      <div style="background: #f4f4f5; border-radius: 8px; padding: 24px; margin-bottom: 32px;">
        <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 16px;">
          <div>
            <h2 style="font-size: 48px; font-weight: bold; margin: 0; color: #18181b;">${score.toFixed(1)}</h2>
            <div style="display: inline-block; margin-top: 8px; padding: 4px 12px; background: ${getSeverityColor(severity)}; border-radius: 4px; font-weight: 500; font-size: 14px; color: white;">
              ${severity}
            </div>
          </div>
        </div>
        
        <div style="margin-top: 16px;">
          <p style="margin: 0 0 8px 0; font-weight: 600; color: #18181b; font-size: 14px;">Vector String</p>
          <p style="margin: 0; font-family: monospace; background: white; padding: 12px; border-radius: 4px; word-break: break-all; font-size: 12px; color: #3f3f46;">
            ${vectorString}
          </p>
        </div>
      </div>

      <div>
        <h3 style="color: #18181b; margin-bottom: 16px; font-size: 18px;">Metric Values</h3>
        <table style="width: 100%; border-collapse: collapse;">
          <thead>
            <tr style="background: #f4f4f5;">
              <th style="padding: 12px; text-align: left; border-bottom: 2px solid #e4e4e7; font-weight: 600; color: #18181b;">Metric</th>
              <th style="padding: 12px; text-align: left; border-bottom: 2px solid #e4e4e7; font-weight: 600; color: #18181b;">Value</th>
            </tr>
          </thead>
          <tbody>
            ${Object.entries(metrics)
              .filter(([_, value]) => value && value !== "X" && value !== "ND")
              .map(
                ([key, value]) => `
              <tr>
                <td style="padding: 12px; border-bottom: 1px solid #e4e4e7; color: #3f3f46; font-weight: 500;">${key}</td>
                <td style="padding: 12px; border-bottom: 1px solid #e4e4e7; color: #3f3f46;">${value}</td>
              </tr>
            `
              )
              .join("")}
          </tbody>
        </table>
      </div>

      <div style="margin-top: 40px; padding-top: 20px; border-top: 2px solid #e4e4e7;">
        <p style="text-align: center; color: #71717a; font-size: 12px; margin: 0;">
          Generated by Quant - Modern CVSS Calculator
        </p>
        <p style="text-align: center; color: #71717a; font-size: 12px; margin: 4px 0 0 0;">
          https://quant.cyberpath-hq.com
        </p>
      </div>
    </div>
  `;

  const element = document.createElement("div");
  element.innerHTML = content;

  const opt = {
    margin: 10,
    filename: `cvss-v${version}-${Date.now()}.pdf`,
    image: { type: "jpeg" as const, quality: 0.98 },
    html2canvas: { scale: 2, useCORS: true },
    jsPDF: { unit: "mm" as const, format: "a4" as const, orientation: "portrait" as const },
  };

  try {
    if (typeof window === "undefined") {
      // Server-side: cannot generate PDF
      throw new Error("PDF generation is only supported in the browser.");
    }

    // Dynamically import the browser-only html2pdf library
    const html2pdfModule = await import("html2pdf.js");
    const html2pdf: any = html2pdfModule?.default ?? html2pdfModule;

    await html2pdf().set(opt).from(element).save();
  } catch (error) {
    console.error("PDF generation failed:", error);
    throw new Error("Failed to generate PDF. Please try again.");
  }
}

/**
 * Get background color for severity level
 */
function getSeverityColor(severity: string): string {
  switch (severity.toLowerCase()) {
    case "none":
      return "#16a34a"; // green
    case "low":
      return "#ca8a04"; // yellow
    case "medium":
      return "#ea580c"; // orange
    case "high":
      return "#dc2626"; // red
    case "critical":
      return "#9333ea"; // purple
    default:
      return "#71717a"; // gray
  }
}
